import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Carousel from "@/componentes/carousel/Carousel";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../componentes/header/header";
import Footer from "../componentes/footer/footer";
import Call from "@/componentes/personalInfo/personalInfo";
import PersonalInfo from "@/componentes/personalInfo/personalInfo";
import CallAction from "@/componentes/callAction/callAction";
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div>
          <PersonalInfo />
        </div>
        <div className="container">
          <Carousel />
        </div>
        <div className="container">
          <CallAction />
        </div>

        <Footer></Footer>
      </main>
    </>
  );
}
